config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "pages#index"
  get 'about_us',to: 'pages#about_us'
  get 'history',to: 'pages#history'
  get 'history_kdci',to: 'pages#history_kdci'
  get 'vision_and_mission',to: 'pages#vision_and_mission'
  get 'association_objective',to: 'pages#association_objective'
  get 'membership',to: 'pages#membership'
  get 'code_of_conducts_and_ethics',to: 'company_documents#code_of_conducts_and_ethics'
  get 'policies_and_implementing_rules',to: 'company_documents#policies_and_implementing_rules'
  get 'acgs_2014',to: 'company_documents#acgs_2014'  

   resources :events_and_features
   resources :galleries
   resources :company_documents
   resources :articles
   resources :partners_and_links
   resources :downloadable_forms
   resources :contact_us
   resources :products_and_services
   resources :memberships
   resources :organizations
   resources :notice_of_agm_disclosures
   resources :notice_of_board_meeting_disclosures
   resources :other_disclosures
   resources :publications

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :file,
	default_url: ""
	validates_attachment_content_type :file, content_type: %w(application/pdf application/zip application/msword application/vnd.ms-office application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
end

app/models/company_document.rb
class CompanyDocument < ActiveRecord::Base
	has_many :company_document_files
	CATEGORIES = ["Governance Manual", "Policies and Implementing Rules", "Corporate Social Responsibilities", "ACGS", "ACGR", "Code of Conducts and Ethics", "Minutes of AGM", "Annual Report", "Audited Financial Statement", "Minutes of Board and Special Meeting", "Board Resolution", "Board Committees", "Board of Trustees", "Meetings and Seminar"]
	YEARS = [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
	accepts_nested_attributes_for :company_document_files, reject_if: :all_blank, allow_destroy: true

	validates :category, presence: true, uniqueness: { scope: [:category, :year] }
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base
end

app/models/downloadable_form.rb
class DownloadableForm < ActiveRecord::Base
	has_attached_file :file,
	default_url: ""
	validates_attachment_content_type :file, content_type: %w(application/pdf application/zip application/msword application/vnd.ms-office application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
end

app/models/events_and_feature.rb
class EventsAndFeature < ActiveRecord::Base
	has_attached_file :photo,
	styles: { 
	  thumb: "80x80>",
	  original: "1024x1024>",
	  standard: "150x150>",
	  large: "500x500>",
	  banner: "750x400>" },
	default_url: ""

	validates :title, presence: true
	validates :description, presence: true 
	validates_attachment_presence :photo
	#validates_attachment_size :photo, :less_than => 5.megabytes  
	validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	has_many :gallery_photos
	accepts_nested_attributes_for :gallery_photos, reject_if: :all_blank, allow_destroy: true

	validates :name, presence: true
end

app/models/gallery_photo.rb
class GalleryPhoto < ActiveRecord::Base
	belongs_to :gallery

has_attached_file :photo,
styles: { 
  thumb: "80x80>", 
  standard: "150x150>",
  large: "500x500>" },
default_url: ""
 
validates_attachment_presence :photo
#validates_attachment_size :photo, :less_than => 50.megabytes  
validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/link_file.rb
class LinkFile < ActiveRecord::Base
	has_attached_file :file,
	default_url: ""
	validates_attachment_content_type :file, content_type: %w(image/jpeg image/jpg image/png image/bmp application/pdf application/zip application/msword application/vnd.ms-office application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)

	validates :file_file_name, presence: true, uniqueness: { scope: [:file_file_name] }
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	QTR = ["1st Qtr", "2nd Qtr", "3rd Qtr", "4th Qtr"]
	validates :date_updated, presence: true
end

app/models/organization.rb
class Organization < ActiveRecord::Base

	has_attached_file :photo,
	styles: { 
	  thumb: "80x80>", 
	  standard: "150x150>",
	  large: "500x500>" },
	default_url: ""
	 
	validates_attachment_presence :photo
	#validates_attachment_size :photo, :less_than => 50.megabytes  
	validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
	validates :title, presence: true, uniqueness: { scope: [:title] }
end

app/models/other_disclosure.rb
class OtherDisclosure < ActiveRecord::Base
	has_attached_file :file,
	default_url: ""
	#validates_attachment_content_type :file, content_type: %w(application/pdf application/zip application/msword application/vnd.ms-office application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
	do_not_validate_attachment_file_type :file
end

app/models/partners_and_link.rb
class PartnersAndLink < ActiveRecord::Base
end

app/models/products_and_service.rb
class ProductsAndService < ActiveRecord::Base

has_attached_file :photo,
styles: { 
  thumb: "80x80>", 
  standard: "150x150>",
  large: "500x500>",
  banner: "750x400>" },
default_url: ""

#validates_attachment_size :photo, :less_than => 5.megabytes  
validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
end

app/models/publication.rb
class Publication < ActiveRecord::Base
	has_attached_file :photo,
	styles: { 
	  thumb: "80x80>",
	  original: "1024x1024>",
	  standard: "150x150>",
	  large: "500x500>",
	  banner: "750x400>" },
	default_url: ""

	has_attached_file :file,
	default_url: ""
	do_not_validate_attachment_file_type :file

	validates :title, presence: true
	validates_attachment_presence :photo
	#validates_attachment_size :photo, :less_than => 5.megabytes  
	validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
end

app/models/vision_and_mission.rb
class VisionAndMission < ApplicationRecord
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController		
	
	def index
		@event_and_feature = EventsAndFeature.all.order("published_at DESC").first
		@prev_event_and_feature = EventsAndFeature.all.order("published_at DESC").second
		@previ_event_and_feature = EventsAndFeature.all.order("published_at DESC").third
		@membership = Membership.first
	end

	def about_us
		@kmba_board_of_trustees = Organization.where("title = ?", "KMBA BOARD OF TRUSTEES").first
    	@kmba_board_of_advisers = Organization.where("title = ?", "KMBA BOARD OF ADVISERS").first
    	@kmba_coordinators = Organization.where("title = ?", "KMBA COORDINATORS").first
	end

	def history
		@history = History.first
	end
	
	def history_kdci	
	end

	def vision_and_mission
		@vision_and_mission = VisionAndMission.first
	end

	def association_objective
		@association_objective = AssociationObjective.first
	end

	def other_services	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_footer.html.haml
.container-footer
	%p.text-muted.credit
		%span.foot
			© #{Time.now.year} KASAGANA-KA Mutual Benefit Association. All Rights Reserved.

app/views/shared/_sidebar.html.haml
%br
#accordion.panel-group
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => root_path, class: "active" }
          HOME
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
          ABOUT US
          %span.glyphicon.glyphicon-chevron-right.pull-right  
    #collapseOne.panel-collapse.collapse
      .panel
        %table.table
          %tr
            %td
              %h5
                %a{:href => history_path } History
          %tr
            %td
              %h5
                %a{:href => vision_and_mission_path } Vision & Mission
          %tr
            %td
              %h5
                %a{:href => association_objective_path } Association Objectives      
          %tr
            %td
              %h5
                %a{:href => organizations_path } Organization
          %tr
            %td
              %h5
                %a{:href => memberships_path } Membership
  .panel.panel-default 
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
          PRODUCTS & SERVICES
          %span.glyphicon.glyphicon-chevron-right.pull-right  
    #collapseTwo.panel-collapse.collapse
      .panel
        %table.table
          - ProductsAndService.all.each do |a|
            %tr
              %td
                %h5
                  = link_to a.title, products_and_service_path(a.id)
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => publications_path }
          PUBLICATIONS
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => articles_path }
          ARTICLES OF INCORPORATION & BY-LAWS
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseThree"}
          DISCLOSURE
          %span.glyphicon.glyphicon-chevron-right.pull-right  
    #collapseThree.panel-collapse.collapse
      .panel
        %table.table
          %tr
            %td
              %h5
                %a{:href => notice_of_agm_disclosures_path } Notice of AGM
          %tr
            %td
              %h5
                %a{:href => notice_of_board_meeting_disclosures_path } Notice of Board Meeting
          %tr
            %td
              %h5
                %a{:href => other_disclosures_path } Other Disclosures
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFour"}
          CORPORATE GOVERNANCE
          %span.glyphicon.glyphicon-chevron-right.pull-right
    #collapseFour.panel-collapse.collapse
      .panel
        %table.table
          - CompanyDocument.where("category = ?", "Governance Manual").each do |a|  
            %tr
              %td
                %h5
                  = link_to "Governance Manual", company_document_path(a.id)
          - CompanyDocument.where("category = ?", "Policies and Implementing Rules").each do |a|
            %tr
              %td
                %h5
                  = link_to "Policies & Implementing Rules", company_document_path(a.id)
          - CompanyDocument.where("category = ?", "Corporate Social Responsibilities").each do |a|
            %tr
              %td
                %h5
                  = link_to "Corporate Social Responsibilities", company_document_path(a.id)        
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-One"}
                  ACGR
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-One.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "ACGR").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-Two"}
                  ACGS
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-Two.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "ACGS").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          - CompanyDocument.where("category = ?", "Code of Conducts and Ethics").each do |a|
            %tr
              %td
                %h5
                  = link_to "Code of Conducts & Ethics", company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-two"}
                  Annual Report
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-two.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Annual Report").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-three"}
                  Minutes of AGM
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-three.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Minutes of AGM").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-four"}
                  Audited Financial Statement
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-four.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Audited Financial Statement").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-five"}
                  Minutes of the Meeting
                  %span.glyphicon.glyphicon-chevron-right.pull-right  
                #collapseThree-five.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Minutes of Board and Special Meeting").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{"data-toggle" => "collapse", :href => "#collapseThree-six"}
                  Board Resolution
                  %span.glyphicon.glyphicon-chevron-right.pull-right  
                #collapseThree-six.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Board Resolution").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-seven"}
                  Board Committees
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-seven.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Board Committees").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-eight"}
                  Board of Trustees
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-eight.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Board of Trustees").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)
          %tr
            %td
              %h5
                %a{ "data-toggle" => "collapse", :href => "#collapseThree-nine"}
                  Meetings & Seminars
                  %span.glyphicon.glyphicon-chevron-right.pull-right
                #collapseThree-nine.panel-collapse.collapse
                  %table.table
                    - CompanyDocument.where("category = ?", "Meetings and Seminar").order("year DESC").each do |a|
                      %tr
                        %td
                          %h5
                            = link_to a.year, company_document_path(a.id)  
          / %tr
          /   %td
          /     %h5
          /       %a{ "data-toggle" => "collapse", :href => "#collapseThree-eight"}
          /         Corporate Social Responsibility
          /         %span.glyphicon.glyphicon-chevron-right.pull-right
          /       #collapseThree-eight.panel-collapse.collapse
          /         %table.table
          /           %tr
          /             %td
          /               %h5
          /                 %a{:href => ""} SICAT
          /           %tr
          /             %td
          /               %h5
          /                 %a{:href => ""} Scholarship
          /           %tr
          /             %td
          /               %h5
          /                 %a{:href => ""} Donation
  .panel.panel-default 
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => partners_and_links_path }
          PARTNERS & LINKS
  .panel.panel-default
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => events_and_features_path }
          EVENTS & FEATURES
  .panel.panel-default  
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => downloadable_forms_path }
          DOWNLOADABLE FORMS
  .panel.panel-default  
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => galleries_path }
          GALLERY
  .panel.panel-default  
    .panel-heading
      %h4
        %a{"data-parent" => "#accordion", :href => contact_us_path }
          CONTACT US  
  .panel-heading
    %h4
      FOLLOW US ON:
      %br
      %a{"data-parent" => "#accordion", :href => "https://www.facebook.com/pages/Kasagana-Ka-Mutual-Benefit-Association/469251036526733" }
        = image_tag("fb.ico", class: "ico")
      %a{"data-parent" => "#accordion", :href => "https://twitter.com/kasaganakaMBA" }
        = image_tag("twi.ico", class: "ico")
      %a{"data-parent" => "#accordion", :href => "https://www.youtube.com/channel/UCJDyX_TvYX7uxuTUNgc2klg" }
        = image_tag("yt.ico", class: "ico")  
%br