config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "pages#index"
  get 'about_us',to: 'pages#about_us'
  get 'history',to: 'pages#history'
  get 'history_kdci',to: 'pages#history_kdci'
  get 'vision_and_mission',to: 'pages#vision_and_mission'
  get 'association_objective',to: 'pages#association_objective'
  get 'membership',to: 'pages#membership'
  get 'code_of_conducts_and_ethics',to: 'company_documents#code_of_conducts_and_ethics'
  get 'policies_and_implementing_rules',to: 'company_documents#policies_and_implementing_rules'
  get 'acgs_2014',to: 'company_documents#acgs_2014'  

   resources :events_and_features
   resources :galleries
   resources :company_documents
   resources :articles
   resources :partners_and_links
   resources :downloadable_forms
   resources :contact_us
   resources :products_and_services
   resources :memberships
   resources :organizations
   resources :notice_of_agm_disclosures
   resources :notice_of_board_meeting_disclosures
   resources :other_disclosures
   resources :publications

end

app/models/notice_of_board_meeting_disclosure.rb
class NoticeOfBoardMeetingDisclosure < ActiveRecord::Base
	has_attached_file :photo,
	styles: { 
	  thumb: "80x80>",
	  original: "1024x1024>",
	  standard: "150x150>",
	  large: "500x500>",
	  banner: "750x400>" },
	default_url: ""

	validates :title, presence: true
	validates :description, presence: true 
	validates_attachment_presence :photo
	#validates_attachment_size :photo, :less_than => 5.megabytes  
	validates_attachment_content_type :photo, content_type: %w(image/jpeg image/jpg image/png image/bmp)
end

app/controllers/notice_of_board_meeting_disclosures_controller.rb
class NoticeOfBoardMeetingDisclosuresController < ApplicationController

  def index
    @notice_of_board_meeting_disclosures = NoticeOfBoardMeetingDisclosure.all
    @notice_of_board_meeting_disclosures = @notice_of_board_meeting_disclosures.page(params[:page]).per(5).order("published_at DESC")
  end

  def new
   	@notice_of_board_meeting_disclosure = NoticeOfBoardMeetingDisclosure.new
  end

  def show
   	@notice_of_board_meeting_disclosure = NoticeOfBoardMeetingDisclosure.find(params[:id])
   	@notice_of_board_meeting_disclosures = NoticeOfBoardMeetingDisclosure.where("id != ?", @notice_of_board_meeting_disclosure.id).order("published_at DESC")
  end

end

app/views/notice_of_board_meeting_disclosures/index.html.erb
<br />
<section class="subhead">
	<h4>Notice of Board Meeting</h4>
</section>
<% @notice_of_board_meeting_disclosures.each do |e| %>
	<div class: "noticeofboardmeetingdisclosurecontent">
		<div class="notice_of_board_meeting_disclosure_img">
			<%= image_tag e.photo.url, id: "ef_img"%>
		</div>
		<h5><%= e.title %></h5>
		<p style="font-size: 13px; color:#8b6504; font-style: italic; fon"><%= image_tag("icon_sandclock.png", :style => "float :left; width: 20px; height: 20px;") %><%= e.published_at.strftime("%B %d, %Y") %></p>
		<p>
			<%= raw e.description.truncate(200).html_safe %>
			<%= link_to "Read more...", notice_of_board_meeting_disclosure_path(e.id) %>
		</p>
	</div>
	<hr />
<% end %>
<%= paginate @notice_of_board_meeting_disclosures %>

app/views/notice_of_board_meeting_disclosures/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="noticeofboardmeetingdisclosurecontent">
			<h3><%= @notice_of_board_meeting_disclosure.title %></h3>	
			<p style="font-size: 15px; color:#8b6504; font-style: italic;"><%= image_tag("icon_sandclock.png", :style => "float :left; width: 20px; height: 20px;") %><%= @notice_of_board_meeting_disclosure.published_at.strftime("%B %d, %Y") %></p>	
				<center>
					<%= image_tag @notice_of_board_meeting_disclosure.photo.url, id: "ind_notice_of_board_meeting_disclosure" %>
				</center>				
			<p>
				<%= @notice_of_board_meeting_disclosure.description.html_safe %>
			</p>
		</div>
	</div>
	<div class="col-md-12">
		<section class="subhead">
			<h4>Other Notice of Board Meeting</h4>
		</section>
			<% @notice_of_board_meeting_disclosures.each do |e| %>
			<div class: "noticeofboardmeetingdisclosurecontent">
				<p>
					<ul>
						<li>
							<%= link_to e.title, notice_of_board_meeting_disclosure_path(e.id) %>
						</li>
					</ul>
				</p>		
			</div>
			<% end %>
		<br />
		<br />
	</div>
</div>